{
 "title": "NodeJS Web App Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "method",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket{route!~\"/metrics|/favicon.ico\"}, method)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket{route!~\"/metrics|/favicon.ico\"}, route)"
    }
   },
   {
    "name": "code",
    "label": "status code",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket{route!~\"/metrics|/favicon.ico\"}, code)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rate (R)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Quantity" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=~\"$method\",route=~\"$route\",code=~\"$code\"}[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Requests by Route",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Quantity" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=~\"$method\",route=~\"$route\",code=~\"$code\"}[1m])) by (route, method)",
     "legendFormat": "{{route}} ({{method}})"
    }
   ]
  },
  { "title": "Errors (E)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Errors 5xx",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=~\"$method\",route=~\"$route\",code=~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errors 5xx",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Quantity" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=~\"$method\",route=~\"$route\",code=~\"5.*\"}[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Errors by Status Code",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Quantity" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{method=~\"$method\",route=~\"$route\",code=~\"5.*|4.*\"}[1m])) by (le, code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Duration (D)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{method=~\"$method\",route=~\"$route\",code=~\"$code\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{method=~\"$method\",route=~\"$route\",code=~\"$code\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{method=~\"$method\",route=~\"$route\",code=~\"$code\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{method=~\"$method\",route=~\"$route\",code=~\"$code\"}[5m])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{method=~\"$method\",route=~\"$route\",code=~\"$code\"}[5m]) /   rate(http_request_duration_seconds_count{method=~\"$method\",route=~\"$route\",code=~\"$code\"}[5m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Response Time by Route and Method",
   "type": "graph",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{method=~\"$method\",route=~\"$route\",code=~\"$code\"}[5m])) by (le, route))",
     "legendFormat": "p99 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{method=~\"$method\", route=~\"$route\", code=~\"$code\"}[5m])) by (le, route))",
     "legendFormat": "p95 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{method=~\"$method\", route=~\"$route\", code=~\"$code\"}[5m])) by (le, route))",
     "legendFormat": "p90 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{method=~\"$method\", route=~\"$route\", code=~\"$code\"}[5m])) by (le, route))",
     "legendFormat": "median {{route}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{method=~\"$method\", route=~\"$route\", code=~\"$code\"}[5m]) /   rate(http_request_duration_seconds_count{method=~\"$method\", route=~\"$route\", code=~\"$code\"}[5m])) by (le, route)",
     "legendFormat": "average {{route}}"
    }
   ]
  }
 ]
}